sudo: required
before_install: gem update --system
dist: trusty
language: ruby
services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE souvenir_shop_test;'

# script:
#   - bundle exec rake test
#   - 'if [ "$TRAVIS_PULL_REQUEST" == false ]; then echo "TRAVIS_PULL_REQUEST is unset, skipping Pronto"; else PULL_REQUEST_ID=${TRAVIS_PULL_REQUEST} bundle exec pronto run -f github_pr; fi'

after_success:
- gem install --no-document pronto pronto-rubocop pronto-brakeman pronto-reek pronto-rails_best_practices pronto-eslint
- PRONTO_GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN} PRONTO_PULL_REQUEST_ID=${TRAVIS_PULL_REQUEST} pronto run -f github_status github_pr -c origin/${TRAVIS_BRANCH}
